Repository CUCWD/edx-platform, pull requests merged in 2022-04, with the labels that each got.

#157 Fix CSV UTF8 Bug
  lms/djangoapps/instructor/views/api.py
  lms/templates/instructor/instructor_dashboard_2/membership.html
Labels: bug, courseware

#155 feat(courseware): Merging in prior release changes.
  cms/envs/common.py
  common/lib/xmodule/xmodule/course_module.py
  common/static/js/vendor/pdfjs/viewer.js
  lms/djangoapps/instructor/views/instructor_dashboard.py
  lms/envs/common.py
  lms/static/coffee/src/.gitignore
  lms/static/coffee/src/resources.coffee
  lms/templates/instructor/instructor_dashboard_2/resources.html
  lms/templates/pdf_viewer.html
  package-lock.json
  package.json
  pavelib/assets.py
Labels: courseware

#156 feat(configuration): Merging in prior release changes.
  cms/envs/production.py
  lms/djangoapps/branding/views.py
  lms/djangoapps/courseware/views/views.py
  lms/envs/common.py
  lms/envs/production.py
  openedx/features/course_experience/views/course_home.py
Labels: configuration

#159 test: run unit-tests on forks
  .github/actions/unit-tests/action.yml
  .github/actions/verify-tests-count/action.yml
  .github/workflows/unit-test-shards.json
  .github/workflows/unit-tests-gh-hosted.yml
  .github/workflows/unit-tests.yml
  .github/workflows/verify-gha-unit-tests-count.yml
  common/lib/capa/capa/safe_exec/tests/test_safe_exec.py
  lms/djangoapps/bulk_user_retirement/tests/test_views.py
  pavelib/paver_tests/test_paver_quality.py
  pavelib/paver_tests/test_xsscommitlint.py
  pavelib/quality.py
  scripts/generic-ci-tests.sh
  scripts/gha-shards-readme.md
  scripts/gha_unit_tests_collector.py
  scripts/unit_test_shards_parser.py
  scripts/xss-commit-linter.sh
Labels: workflow

#148 feat(qualtrics-survey): merging from Koa to Maple
  cms/envs/common.py
  cms/envs/devstack.py
  common/lib/xmodule/xmodule/course_module.py
  lms/envs/common.py
  lms/envs/devstack.py
Labels: courseware

#153 feat(bigcommerce_app) Merge in prior release changes.
  .github/workflows/pylint-checks.yml
  .github/workflows/unit-test-shards.json
  .gitignore
  common/djangoapps/student/views/dashboard.py
  common/djangoapps/third_party_auth/admin.py
  common/djangoapps/third_party_auth/migrations/0006_emailproviderconfig.py
  common/djangoapps/third_party_auth/migrations/0007_auto_20220121_1956.py
  common/djangoapps/third_party_auth/models.py
  common/djangoapps/third_party_auth/provider.py
  common/djangoapps/third_party_auth/strategy.py
  db_keyword_overrides.yml
  lms/djangoapps/bigcommerce_app/__init__.py
  lms/djangoapps/bigcommerce_app/apps.py
  lms/djangoapps/bigcommerce_app/callbacks/__init__.py
  lms/djangoapps/bigcommerce_app/callbacks/urls.py
  lms/djangoapps/bigcommerce_app/callbacks/views.py
  lms/djangoapps/bigcommerce_app/events/__init__.py
  lms/djangoapps/bigcommerce_app/events/course_enrollment.py
  lms/djangoapps/bigcommerce_app/handlers.py
  lms/djangoapps/bigcommerce_app/migrations/0001_initial.py
  lms/djangoapps/bigcommerce_app/migrations/0002_auto_20211015_1907.py
  lms/djangoapps/bigcommerce_app/migrations/0003_auto_20211015_1936.py
  lms/djangoapps/bigcommerce_app/migrations/0004_auto_20211015_1946.py
  lms/djangoapps/bigcommerce_app/migrations/0005_auto_20211019_0209.py
  lms/djangoapps/bigcommerce_app/migrations/0006_auto_20211021_1916.py
  lms/djangoapps/bigcommerce_app/migrations/0007_auto_20211021_2015.py
  lms/djangoapps/bigcommerce_app/migrations/0008_auto_20211021_2019.py
  lms/djangoapps/bigcommerce_app/migrations/__init__.py
  lms/djangoapps/bigcommerce_app/models.py
  lms/djangoapps/bigcommerce_app/single_click/__init__.py
  lms/djangoapps/bigcommerce_app/single_click/urls.py
  lms/djangoapps/bigcommerce_app/single_click/views.py
  lms/djangoapps/bigcommerce_app/tests/__init__.py
  lms/djangoapps/bigcommerce_app/tests/factories.py
  lms/djangoapps/bigcommerce_app/tests/test_models.py
  lms/djangoapps/bigcommerce_app/utils.py
  lms/envs/common.py
  lms/envs/test.py
  lms/static/js/student_account/views/account_settings_factory.js
  lms/static/js/student_account/views/account_settings_view.js
  lms/templates/bigcommerce_app/index.html
  lms/templates/bigcommerce_app/single-click-app-base.html
  lms/templates/student_account/account_settings.html
  lms/urls.py
  openedx/core/djangoapps/user_api/accounts/settings_views.py
  openedx/core/djangoapps/user_authn/cookies.py
  requirements/edx/development.txt
  requirements/edx/private.in
  requirements/edx/private.txt
  requirements/edx/testing.in
  requirements/edx/testing.txt
Labels: bigcommerce

#161 feat(badging): Handling cases when Badge tab is disabled.
  lms/djangoapps/courseware/tabs.py
  openedx/features/course_experience/tests/views/test_course_home.py
  openedx/features/course_experience/utils.py
Labels: badging

#146 feat(key-terms): Merging from koa to maple
  cms/djangoapps/contentstore/courseware_index.py
  cms/envs/common.py
  cms/envs/devstack.py
  cms/envs/production.py
  common/lib/xmodule/xmodule/tabs.py
  lms/djangoapps/course_home_api/glossary/__init__.py
  lms/djangoapps/course_home_api/glossary/serializers.py
  lms/djangoapps/course_home_api/glossary/views.py
  lms/djangoapps/course_home_api/urls.py
  lms/djangoapps/courseware/tabs.py
  lms/djangoapps/courseware/views/views.py
  lms/envs/common.py
  lms/envs/devstack.py
  lms/envs/production.py
  lms/templates/courseware/glossary.html
  lms/urls.py
  openedx/core/djangoapps/content/course_overviews/tests/test_course_overviews.py
  setup.py
Labels: key-terms

#164 feat(key-terms): Enable `Key Terms Dashboard` in Studio.
  cms/djangoapps/contentstore/utils.py
  cms/templates/widgets/header.html
Labels: key-terms
